# Generated by Django 4.1.6 on 2023-08-02 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 11, 49, 57, 134957, tzinfo=datetime.timezone.utc)),
        ),
    ]
